name: Bug Report
description: Template for bug report
title: "[Bug]: "
labels: ["Bug", "NotFixed"]
assignees:
  - EncryptSL
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Remember only last version is supported !
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: What version of plugin are you running?
      placeholder: ex. 1.1.6-SNAPSHOT
    validations:
      required: true
  - type: dropdown
    id: serversoftware
    attributes:
      label: You detected problem on this server platform ?
      multiple: true
      options:
        - PaperMC
        - PurpurMC
    validations:
      required: true
  - type: textarea
    id: version_verbose
    attributes:
      label: Version /version - output
      description: Please copy and paste version output from console thanks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
